import { Injectable, InternalServerErrorException, NotFoundException } from '@nestjs/common';
import * as path from 'path';
import * as fs from 'fs';
import { spawn, ChildProcess } from 'child_process';

@Injectable()
export class TrainingService {
  private currentProcess: ChildProcess | null = null;
  private currentLogPath: string | null = null;
  private trainingDir: string;
  private pythonPath: string;
  private scriptPath: string;
  private accelerateConfig: string;

  constructor() {
    const rootDir = process.cwd(); // apps/api
    this.trainingDir = path.resolve(rootDir, '../../training/F5-TTS');
    this.pythonPath = path.join(this.trainingDir, 'venv/Scripts/python.exe');
    this.scriptPath = path.join(this.trainingDir, 'train_tounsi.py');
    const accelerateConfigPath = path.resolve(rootDir, '../../training/accelerate_cpu_config.yaml');
    this.accelerateConfig = accelerateConfigPath;
    
    // Ensure log dir exists
    const logDir = path.resolve(rootDir, 'logs/training');
    if (!fs.existsSync(logDir)) {
      fs.mkdirSync(logDir, { recursive: true });
    }
  }

  async startTraining(config: { maxSteps?: number; batchSize?: number; learningRate?: number }) {
    if (this.currentProcess) {
      throw new InternalServerErrorException('Training is already in progress');
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    this.currentLogPath = path.resolve(process.cwd(), `logs/training/session_${timestamp}.log`);
    const logStream = fs.createWriteStream(this.currentLogPath, { flags: 'a' });

    console.log(`Starting training session, logging to ${this.currentLogPath}`);
    
    // Args for accelerate launch
    // accelerate launch --config_file ... train_tounsi.py args...
    // We use the python executable from venv, but to run accelerate we might need:
    // "python -m accelerate.commands.launch --config_file ..."
    // This is safer than relying on 'accelerate' being in path.
    
    const args = [
      '-m', 'accelerate.commands.launch',
      '--config_file', this.accelerateConfig,
      this.scriptPath,
      '--data_dir', path.resolve(this.trainingDir, '../tounsi_dataset'),
      '--vocab_path', path.resolve(this.trainingDir, '../tounsi_dataset/vocab.txt'),
      '--output_dir', path.resolve(this.trainingDir, '../outputs/tounsi_training'),
      '--max_steps', (config.maxSteps || 5000).toString(),
      '--batch_size', (config.batchSize || 1).toString(),
      '--learning_rate', (config.learningRate || 1e-4).toString(),
      '--save_steps', '500', 
      '--logging_steps', '1'
    ];

    try {
      this.currentProcess = spawn(this.pythonPath, args, {
        cwd: this.trainingDir,
        env: { ...process.env, PYTHONUNBUFFERED: '1' } 
      });

      this.currentProcess.stdout.pipe(logStream);
      this.currentProcess.stderr.pipe(logStream);

      this.currentProcess.on('close', (code) => {
        console.log(`Training process exited with code ${code}`);
        this.currentProcess = null;
        logStream.end();
      });

      this.currentProcess.on('error', (err) => {
        console.error('Failed to spawn training process:', err);
        this.currentProcess = null;
        logStream.end();
      });

      return { status: 'started', pid: this.currentProcess.pid, logPath: this.currentLogPath };
    } catch (e) {
      console.error(e);
      throw new InternalServerErrorException(`Failed to start training: ${e.message}`);
    }
  }

  async stopTraining() {
    if (!this.currentProcess) {
      throw new NotFoundException('No training process running');
    }
    
    // On Windows, killing the parent python process might not kill children generated by accelerate?
    // But usually it does.
    // tree-kill might be needed for robust kill, but currentProcess.kill() sends SIGTERM.
    const killed = this.currentProcess.kill();
    if (!killed) {
        throw new InternalServerErrorException('Failed to kill process');
    }
    this.currentProcess = null;
    return { status: 'stopped' };
  }

  async getStatus() {
    let logs = '';
    if (this.currentLogPath && fs.existsSync(this.currentLogPath)) {
        // Read last N lines?
        // Simple implementation: Read whole file? Might be huge.
        // Read last 10KB.
        const stats = fs.statSync(this.currentLogPath);
        const size = stats.size;
        const bufferSize = 10 * 1024;
        const start = Math.max(0, size - bufferSize);
        const stream = fs.createReadStream(this.currentLogPath, { start, end: size });
        
        // Convert stream to string promise
        logs = await new Promise((resolve) => {
            const chunks = [];
            stream.on('data', (chunk) => chunks.push(chunk));
            stream.on('end', () => resolve(Buffer.concat(chunks).toString()));
        });
    }

    return {
      running: !!this.currentProcess,
      pid: this.currentProcess?.pid,
      logs: logs
    };
  }
}
